version: '3.6'
services:
  kibana:
    image: elastic/kibana:6.2.2
    environment:
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  elasticsearch:
    image: elastic/elasticsearch:6.2.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"